import type { Vehicle } from "~/components/shared/types";

/** Fisher-Yates shuffle — returns a new randomly-ordered copy. */
function shuffle<T>(arr: readonly T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = copy[i];
    copy[i] = copy[j] as T;
    copy[j] = tmp as T;
  }
  return copy;
}

/**
 * Separate mock API for "Because You Viewed" section.
 * Currently returns the same data as other sources but kept separate
 * so it can be swapped out later without changing callers.
 */
export function fetchBecauseYouViewedCars(): Vehicle[] {
  return shuffle(becauseViewedVehicles);
}

// NOTE: `becauseViewedVehicles` is intentionally a separate copy of the
// mock dataset so this API does not reference `mockVehicles` directly.
export const becauseViewedVehicles = [
  {
    id: 1,
    title: "2023 Toyota Corolla Cross",
    make: "toyota",
    model: "corolla-cross",
    variant: "le",
    year: 2023,
    vin: "JTDEPMAE5PJ100001",
    price: 31_250,
    image: [
      "/images/vehicles/corolla-cross.png",
      "/images/vehicles/rav4-blue.png",
      "/images/vehicles/rav4-white.png",
    ],
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "18,000mi",
    mileage: 18_000,
    bodyType: "SUV",
    match: 39,
    labels: [],
    owners: 2,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Black SofTex",
    intColorCode: "#1B1B1B",
  },
  {
    id: 2,
    title: "2022 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-xle",
    year: 2022,
    vin: "2T3P1RFV8NW100002",
    price: 31_250,
    image: ["/images/vehicles/rav4-blue.png", "/images/vehicles/corolla-cross.png"],
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,600mi",
    mileage: 24_600,
    bodyType: "Coupe",
    match: 56,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
  },
  {
    id: 3,
    title: "2023 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-limited",
    year: 2023,
    vin: "2T3P1RFV5PW100003",
    price: 33_250,
    oldPrice: 34_995,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    mileage: 21_000,
    bodyType: "Coupe",
    match: 79,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 4,
    title: "2023 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-se",
    year: 2023,
    vin: "2T3P1RFV3PW100004",
    price: 33_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    mileage: 21_000,
    bodyType: "SUV",
    match: 79,
    labels: [],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 5,
    title: "2024 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-xle-premium",
    year: 2024,
    vin: "2T3P1RFV0RW100005",
    price: 29_990,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,500mi",
    mileage: 24_500,
    bodyType: "SUV",
    match: 85,
    labels: [],
    owners: 2,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
  },
  {
    id: 6,
    title: "2022 Toyota Yaris Cross Hybrid Active",
    make: "toyota",
    model: "yaris-cross",
    variant: "hybrid-active",
    year: 2022,
    vin: "JTDKN3DU5N0100006",
    price: 30_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "16,000mi",
    mileage: 16_000,
    bodyType: "SUV",
    match: 54,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 7,
    title: "2023 Toyota Corolla Cross",
    make: "toyota",
    model: "corolla-cross",
    variant: "xle",
    year: 2023,
    vin: "JTDEPMAE7PJ100007",
    price: 31_250,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "18,000mi",
    mileage: 18_000,
    bodyType: "SUV",
    match: 81,
    labels: [],
    owners: 3,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 8,
    title: "2024 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-limited",
    year: 2024,
    vin: "2T3P1RFV5RW100008",
    price: 33_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "5,000mi",
    mileage: 12_000,
    bodyType: "Coupe",
    match: 57,
    labels: [],
    owners: 2,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 9,
    title: "2020 Toyota Venza Limited Edition",
    make: "toyota",
    model: "venza",
    variant: "limited",
    year: 2020,
    vin: "JTEBU5JR5L5100009",
    price: 32_000,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "9,000mi",
    mileage: 13_000,
    bodyType: "SUV",
    match: 74,
    labels: [],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 10,
    title: "2022 Toyota Yaris Cross Hybrid Active",
    make: "toyota",
    model: "yaris-cross",
    variant: "hybrid-active",
    year: 2022,
    vin: "JTDKN3DU3N0100010",
    price: 24_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "11,050mi",
    mileage: 11_050,
    bodyType: "SUV",
    match: 72,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 11,
    title: "2025 Toyota RAV4 Limited Edition",
    make: "toyota",
    model: "rav4",
    variant: "limited",
    year: 2025,
    vin: "2T3P1RFV7SW100011",
    price: 30_900,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "15,000mi",
    mileage: 15_000,
    bodyType: "SUV",
    match: 55,
    labels: ["Low Price"],
    owners: 1,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
  },
  {
    id: 12,
    title: "2020 Toyota Corolla Cross Limited Edition",
    make: "toyota",
    model: "corolla-cross",
    variant: "limited",
    year: 2020,
    vin: "JTDEPMAE0L0100012",
    price: 31_250,
    oldPrice: 34_568,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "17,200mi",
    mileage: 17_200,
    bodyType: "SUV",
    match: 76,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 13,
    title: "2025 Toyota RAV4 Limited Edition",
    make: "toyota",
    model: "rav4",
    variant: "limited",
    year: 2025,
    vin: "2T3P1RFV9SW100013",
    price: 34_250,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    mileage: 21_000,
    bodyType: "SUV",
    match: 74,
    labels: [],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 14,
    title: "2023 Toyota Camry XSE",
    make: "toyota",
    model: "camry",
    variant: "xse",
    year: 2023,
    vin: "4T1K61AK5PU100014",
    price: 28_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "12,500mi",
    mileage: 12_500,
    bodyType: "Sedan",
    match: 88,
    labels: ["Good Price"],
    owners: 1,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
  },
  {
    id: 15,
    title: "2024 Toyota Highlander Hybrid",
    make: "toyota",
    model: "highlander",
    variant: "hybrid-platinum",
    year: 2024,
    vin: "5TDFZRBH5RS100015",
    price: 45_990,
    oldPrice: 48_500,
    image: [
      "/images/vdp/PDP_3.png",
      "/images/vdp/PDP_2.png",
      "/images/vdp/PDP_1.png",
      "/images/vdp/PDP_4.png",
      "/images/vdp/PDP_5.png",
      "/images/vdp/PDP_6.png",
    ],
    miles: "Park Place Toyota - 8.5mi",
    odometer: "8,200mi",
    mileage: 14_000,
    bodyType: "SUV",
    match: 91,
    labels: ["Price Drop"],
    owners: 2,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 16,
    title: "2022 Toyota Tacoma TRD Pro — Truck",
    make: "toyota",
    model: "tacoma",
    variant: "trd-pro",
    year: 2022,
    vin: "3TMCZ5AN5NM100016",
    price: 43_750,
    image: "/images/vehicles/truck.webp",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "28,400mi",
    mileage: 28_400,
    bodyType: "Truck",
    match: 67,
    labels: ["Truck"],
    owners: 2,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
  },
  {
    id: 17,
    title: "2023 Toyota Tundra CrewMax — Truck",
    make: "toyota",
    model: "tundra",
    variant: "crewmax-sr5",
    year: 2023,
    vin: "5TFDY5F16PX100017",
    price: 53_900,
    image: "/images/vehicles/truck.webp",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "15,800mi",
    mileage: 15_800,
    bodyType: "Truck",
    match: 72,
    labels: ["Excellent Price", "Truck"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 18,
    title: "2024 Toyota Prius Prime",
    make: "toyota",
    model: "prius",
    variant: "prime-xle",
    year: 2024,
    vin: "JTDKN3DP5R3100018",
    price: 34_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "3,200mi",
    mileage: 10_500,
    bodyType: "Sedan",
    match: 94,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 19,
    title: "2021 Toyota 4Runner TRD Off-Road",
    make: "toyota",
    model: "4runner",
    variant: "trd-off-road",
    year: 2021,
    vin: "JTEBU5JR3M5100019",
    price: 39_900,
    oldPrice: 42_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "35,600mi",
    mileage: 35_600,
    bodyType: "SUV",
    match: 63,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
  },
  {
    id: 20,
    title: "2023 Toyota Sienna Platinum",
    make: "toyota",
    model: "sienna",
    variant: "platinum",
    year: 2023,
    vin: "5TDKRKEC5PS100020",
    price: 48_750,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "19,200mi",
    mileage: 19_200,
    bodyType: "Van",
    match: 78,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
] as Vehicle[];
