// ─── Enrichment types (previously in vehicle-enrichments.ts) ────────────────

export type FuelType =
  | "Gasoline"
  | "Hybrid"
  | "Plug-in Hybrid"
  | "Electric"
  | "Hydrogen"
  | "Diesel"
  | "Flex Fuel";

export type Drivetrain = "AWD" | "FWD" | "RWD" | "4WD";
export type Transmission = "Automatic" | "CVT" | "Manual";

export interface VehicleFeatures {
  comfort: string[];
  exterior: string[];
  performance: string[];
  safety: string[];
  tech: string[];
}

export interface VehicleEstimation {
  apr: string;
  creditScore: string;
  estimatedMonthlyPayment: string;
  termLength: string;
}

export interface Vehicle {
  bodyType: "Sedan" | "SUV" | "Truck" | "Hatchback" | "Van" | "Convertible" | "Coupe" | "Wagon";
  drivetrain: Drivetrain;
  estimation?: VehicleEstimation;
  extColorCode: string;
  extColorName: string;
  features: VehicleFeatures;

  // ── Enrichment fields (previously in vehicle-enrichments.ts) ──
  fuelType: FuelType;
  // ── Core fields ──
  id: number;
  image: string | string[];
  inspection160: boolean;
  intColorCode: string;
  intColorName: string;
  labels: string[];
  make: string;
  match: number;
  mileage: number;
  miles: string;
  model: string;
  odometer: string;
  oldPrice?: number;
  owners: number;
  price: number;
  seatingCapacity: string[];
  title: string;
  transmission: Transmission;
  variant: string;
  vin: string;
  year: number;
}

/** Compute a default estimation summary from the vehicle price. */
export function getVehicleEstimation(vehicle: Vehicle): VehicleEstimation {
  if (vehicle.estimation) {
    return vehicle.estimation;
  }
  const apr = 5.49;
  const termMonths = 60;
  const downPayment = 2500;
  const principal = vehicle.price - downPayment;
  const monthlyRate = apr / 100 / 12;
  const monthly = Math.round((principal * monthlyRate) / (1 - (1 + monthlyRate) ** -termMonths));
  return {
    creditScore: "Excellent (800+) FICO® Score",
    apr: `${apr}%`,
    termLength: `$${downPayment.toLocaleString()}`,
    estimatedMonthlyPayment: `$${monthly}`,
  };
}

// ─── Shared feature sets (reduces repetition across vehicle records) ─────────

const BASE_SAFETY = ["PCS", "LDA", "Backup Camera", "FCW"];
const FULL_SAFETY = [...BASE_SAFETY, "BSM", "ACC", "RCTA", "LTA", "RSA", "Auto High Beams"];
const TRD_SAFETY = [...BASE_SAFETY, "BSM", "ACC", "RCTA", "Parking Sensors"];

const BASE_TECH = ["Apple CarPlay", "Android Auto", "Bluetooth", "USB-C"];
const MID_TECH = [...BASE_TECH, "Wireless Charging", "Navigation", "Digital Cluster"];
const FULL_TECH = [
  ...MID_TECH,
  "Wireless CarPlay",
  "Wireless Android",
  "Heads-Up Display",
  "12+ Screen",
];

const BASE_COMFORT = ["Keyless", "Push Start", "Dual Climate"];
const MID_COMFORT = [...BASE_COMFORT, "Heated Seats", "Power Liftgate", "Heated Wheel"];
const FULL_COMFORT = [
  ...MID_COMFORT,
  "Ventilated",
  "Heated Rear",
  "Remote Start",
  "Moonroof",
  "Memory Seats",
];
const LUXURY_COMFORT = [...FULL_COMFORT, "Panoramic", "Tri-Zone", "Hands-Free"];

const BASE_EXT = ["LED Headlights", "LED Taillights"];
const FULL_EXT = [...BASE_EXT, "LED Fog", "Folding Mirrors", "Adaptive Lights"];
const TRD_EXT = [...FULL_EXT, "Running Boards", "Roof Rails"];
const TRUCK_EXT = [...TRD_EXT, "Tow Package", "Bed Liner"];

// ─────────────────────────────────────────────────────────────────────────────

export const mockVehicles: Vehicle[] = [
  {
    id: 1,
    title: "2023 Toyota Corolla Cross",
    make: "toyota",
    model: "corolla-cross",
    variant: "le",
    year: 2023,
    vin: "JTDEPMAE5PJ100001",
    price: 31_250,
    image: [
      "/images/vehicles/corolla-cross.png",
      "/images/vehicles/rav4-blue.png",
      "/images/vehicles/rav4-white.png",
    ],
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "18,000mi",
    mileage: 18_000,
    bodyType: "SUV",
    match: 39,
    labels: [],
    owners: 2,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Black SofTex",
    intColorCode: "#1B1B1B",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: BASE_SAFETY,
      comfort: MID_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: [],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 2,
    title: "2022 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-xle",
    year: 2022,
    vin: "2T3P1RFV8NW100002",
    price: 31_250,
    image: ["/images/vehicles/rav4-blue.png", "/images/vehicles/corolla-cross.png"],
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,600mi",
    mileage: 24_600,
    bodyType: "SUV",
    match: 56,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: [...BASE_SAFETY, "BSM", "RCTA"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: BASE_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 3,
    title: "2023 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-limited",
    year: 2023,
    vin: "2T3P1RFV5PW100003",
    price: 33_250,
    oldPrice: 34_995,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    mileage: 21_000,
    bodyType: "SUV",
    match: 79,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 4,
    title: "2023 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-se",
    year: 2023,
    vin: "2T3P1RFV3PW100004",
    price: 33_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    mileage: 21_000,
    bodyType: "SUV",
    match: 79,
    labels: [],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: [...BASE_SAFETY, "BSM", "ACC", "RCTA"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: BASE_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 5,
    title: "2024 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-xle-premium",
    year: 2024,
    vin: "2T3P1RFV0RW100005",
    price: 29_990,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,500mi",
    mileage: 24_500,
    bodyType: "SUV",
    match: 85,
    labels: [],
    owners: 2,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: MID_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 6,
    title: "2022 Toyota Yaris Cross Hybrid Active",
    make: "toyota",
    model: "yaris-cross",
    variant: "hybrid-active",
    year: 2022,
    vin: "JTDKN3DU5N0100006",
    price: 30_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "16,000mi",
    mileage: 16_000,
    bodyType: "Wagon",
    match: 54,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
    fuelType: "Hybrid",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Hybrid"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 7,
    title: "2023 Toyota Corolla Cross",
    make: "toyota",
    model: "corolla-cross",
    variant: "xle",
    year: 2023,
    vin: "JTDEPMAE7PJ100007",
    price: 31_250,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "18,000mi",
    mileage: 18_000,
    bodyType: "SUV",
    match: 81,
    labels: [],
    owners: 3,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
    fuelType: "Gasoline",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: [...BASE_SAFETY, "BSM", "ACC"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: FULL_EXT,
      performance: ["AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 8,
    title: "2024 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-limited",
    year: 2024,
    vin: "2T3P1RFV5RW100008",
    price: 33_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "5,000mi",
    mileage: 12_000,
    bodyType: "SUV",
    match: 57,
    labels: [],
    owners: 2,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: FULL_SAFETY,
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: BASE_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 9,
    title: "2020 Toyota Venza Limited Edition",
    make: "toyota",
    model: "venza",
    variant: "limited",
    year: 2020,
    vin: "JTEBU5JR5L5100009",
    price: 32_000,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "9,000mi",
    mileage: 13_000,
    bodyType: "SUV",
    match: 74,
    labels: [],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: [],
  },
  {
    id: 10,
    title: "2022 Toyota Yaris Cross Hybrid Active",
    make: "toyota",
    model: "yaris-cross",
    variant: "hybrid-active",
    year: 2022,
    vin: "JTDKN3DU3N0100010",
    price: 24_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "11,050mi",
    mileage: 11_050,
    bodyType: "SUV",
    match: 72,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Hybrid",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Hybrid"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 11,
    title: "2025 Toyota RAV4 Limited Edition",
    make: "toyota",
    model: "rav4",
    variant: "limited",
    year: 2025,
    vin: "2T3P1RFV7SW100011",
    price: 30_900,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "15,000mi",
    mileage: 15_000,
    bodyType: "SUV",
    match: 55,
    labels: ["Low Price"],
    owners: 1,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
    fuelType: "Gasoline",
    drivetrain: "AWD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["AWD/4WD", "Sport Mode"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 12,
    title: "2020 Toyota Corolla Cross Limited Edition",
    make: "toyota",
    model: "corolla-cross",
    variant: "limited",
    year: 2020,
    vin: "JTDEPMAE0L0100012",
    price: 31_250,
    oldPrice: 34_568,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "17,200mi",
    mileage: 17_200,
    bodyType: "SUV",
    match: 76,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: [],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 13,
    title: "2025 Toyota RAV4 Limited Edition",
    make: "toyota",
    model: "rav4",
    variant: "limited",
    year: 2025,
    vin: "2T3P1RFV9SW100013",
    price: 34_250,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    mileage: 21_000,
    bodyType: "SUV",
    match: 74,
    labels: [],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Gasoline",
    drivetrain: "AWD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 14,
    title: "2023 Toyota Camry XSE",
    make: "toyota",
    model: "camry",
    variant: "xse",
    year: 2023,
    vin: "4T1K61AK5PU100014",
    price: 28_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "12,500mi",
    mileage: 12_500,
    bodyType: "Sedan",
    match: 88,
    labels: ["Good Price"],
    owners: 1,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: [...BASE_SAFETY, "BSM", "ACC", "LDA"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: FULL_EXT,
      performance: ["Sport Mode", "V6"],
    },
    seatingCapacity: [],
  },
  {
    id: 15,
    title: "2024 Toyota Highlander Hybrid",
    make: "toyota",
    model: "highlander",
    variant: "hybrid-platinum",
    year: 2024,
    vin: "5TDFZRBH5RS100015",
    price: 45_990,
    oldPrice: 48_500,
    image: [
      "/images/vdp/PDP_3.png",
      "/images/vdp/PDP_2.png",
      "/images/vdp/PDP_1.png",
      "/images/vdp/PDP_4.png",
      "/images/vdp/PDP_5.png",
      "/images/vdp/PDP_6.png",
    ],
    miles: "Park Place Toyota - 8.5mi",
    odometer: "8,200mi",
    mileage: 14_000,
    bodyType: "SUV",
    match: 91,
    labels: ["Price Drop"],
    owners: 2,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Third Row", "7 Passenger", "Captain's Chairs", "Split Folding"],
  },
  {
    id: 16,
    title: "2022 Toyota Tacoma TRD Pro — Truck",
    make: "toyota",
    model: "tacoma",
    variant: "trd-pro",
    year: 2022,
    vin: "3TMCZ5AN5NM100016",
    price: 43_750,
    image: "/images/vehicles/truck.webp",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "28,400mi",
    mileage: 28_400,
    bodyType: "Truck",
    match: 67,
    labels: ["Truck"],
    owners: 2,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
    fuelType: "Gasoline",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: TRD_SAFETY,
      comfort: [...BASE_COMFORT, "Heated Seats", "Heated Wheel"],
      tech: MID_TECH,
      exterior: TRUCK_EXT,
      performance: ["AWD/4WD", "TRD Suspension", "Multi-Terrain", "Crawl Control", "Locking Diff"],
    },
    seatingCapacity: [],
  },
  {
    id: 17,
    title: "2023 Toyota Tundra CrewMax — Truck",
    make: "toyota",
    model: "tundra",
    variant: "crewmax-sr5",
    year: 2023,
    vin: "5TFDY5F16PX100017",
    price: 53_900,
    image: "/images/vehicles/truck.webp",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "15,800mi",
    mileage: 15_800,
    bodyType: "Truck",
    match: 72,
    labels: ["Excellent Price", "Truck"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Gasoline",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: [...BASE_SAFETY, "BSM", "RCTA", "360 Camera", "Parking Sensors"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: TRUCK_EXT,
      performance: ["AWD/4WD", "Turbo", "HFORCE MAX"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 18,
    title: "2024 Toyota Prius Prime",
    make: "toyota",
    model: "prius",
    variant: "prime-xle",
    year: 2024,
    vin: "JTDKN3DP5R3100018",
    price: 34_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "3,200mi",
    mileage: 10_500,
    bodyType: "Sedan",
    match: 94,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
    fuelType: "Plug-in Hybrid",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: [...MID_COMFORT, "Solar Roof"],
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "PHEV"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 19,
    title: "2021 Toyota 4Runner TRD Off-Road",
    make: "toyota",
    model: "4runner",
    variant: "trd-off-road",
    year: 2021,
    vin: "JTEBU5JR3M5100019",
    price: 39_900,
    oldPrice: 42_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "35,600mi",
    mileage: 35_600,
    bodyType: "SUV",
    match: 63,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
    fuelType: "Gasoline",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: TRD_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: TRD_EXT,
      performance: ["AWD/4WD", "TRD Suspension", "Multi-Terrain", "Crawl Control", "Locking Diff"],
    },
    seatingCapacity: ["Third Row", "7 Passenger", "Split Folding"],
  },
  {
    id: 20,
    title: "2023 Toyota Sienna Platinum",
    make: "toyota",
    model: "sienna",
    variant: "platinum",
    year: 2023,
    vin: "5TDKRKEC5PS100020",
    price: 48_750,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "19,200mi",
    mileage: 19_200,
    bodyType: "Van",
    match: 78,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Third Row", "8 Passenger", "Captain's Chairs", "Power Front", "Fold Flat"],
  },
  {
    id: 21,
    title: "2024 Toyota Crown Platinum",
    make: "toyota",
    model: "crown",
    variant: "platinum",
    year: 2024,
    vin: "JTHDP5BC5R5100021",
    price: 51_200,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "6,100mi",
    mileage: 11_000,
    bodyType: "Sedan",
    match: 86,
    labels: ["Good Price"],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD", "Sport Mode"],
    },
    seatingCapacity: [],
  },
  {
    id: 22,
    title: "2022 Toyota GR86 Premium",
    make: "toyota",
    model: "gr86",
    variant: "premium",
    year: 2022,
    vin: "JF1ZNAE12N8100022",
    price: 29_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "22,300mi",
    mileage: 22_300,
    bodyType: "Sedan",
    match: 71,
    labels: [],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
    fuelType: "Gasoline",
    drivetrain: "RWD",
    transmission: "Manual",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Sport Mode"],
    },
    seatingCapacity: [],
  },
  {
    id: 23,
    title: "2023 Toyota Camry Solara Convertible",
    make: "toyota",
    model: "camry-solara",
    variant: "se-v6-convertible",
    year: 2023,
    vin: "WZ1DB0C08PW100023",
    price: 54_900,
    oldPrice: 58_200,
    image: "/images/vehicles/convertible.webp",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "11,500mi",
    mileage: 11_500,
    bodyType: "Convertible",
    match: 82,
    labels: ["Price Drop", "Excellent Price"],
    owners: 3,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: [...BASE_COMFORT, "Heated Seats", "Leather"],
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Sport Mode"],
    },
    seatingCapacity: [],
  },
  {
    id: 24,
    title: "2024 Toyota bZ4X Limited",
    make: "toyota",
    model: "bz4x",
    variant: "limited",
    year: 2024,
    vin: "JTMAB3FV5R5100024",
    price: 43_500,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "4,800mi",
    mileage: 12_000,
    bodyType: "SUV",
    match: 89,
    labels: [],
    owners: 2,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Electric",
    drivetrain: "AWD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 25,
    title: "2021 Toyota Avalon TRD",
    make: "toyota",
    model: "avalon",
    variant: "trd",
    year: 2021,
    vin: "4T1FZ1FB3MU100025",
    price: 18_400,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "31,200mi",
    mileage: 31_200,
    bodyType: "Sedan",
    match: 58,
    labels: ["Low Price"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: [...BASE_SAFETY, "BSM", "ACC"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: [...BASE_EXT, "LED Fog"],
      performance: ["Sport Mode", "V6"],
    },
    seatingCapacity: [],
  },
  {
    id: 26,
    title: "2023 Toyota C-HR Nightshade",
    make: "toyota",
    model: "c-hr",
    variant: "nightshade",
    year: 2023,
    vin: "NMTKHMBX0PR100026",
    price: 19_900,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "14,600mi",
    mileage: 14_600,
    bodyType: "SUV",
    match: 75,
    labels: ["Good Price"],
    owners: 2,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: [...BASE_EXT, "Folding Mirrors"],
      performance: [],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 27,
    title: "2024 Toyota Sequoia Capstone",
    make: "toyota",
    model: "sequoia",
    variant: "capstone",
    year: 2024,
    vin: "5TDYY5G14RS100027",
    price: 78_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "2,100mi",
    mileage: 10_500,
    bodyType: "SUV",
    match: 92,
    labels: [],
    owners: 3,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
    fuelType: "Hybrid",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD", "Trailer Sway"],
    },
    seatingCapacity: ["Third Row", "8 Passenger", "Captain's Chairs", "Power Front", "Fold Flat"],
  },
  {
    id: 28,
    title: "2022 Toyota GR Corolla Core",
    make: "toyota",
    model: "gr-corolla",
    variant: "core",
    year: 2022,
    vin: "JTEAC3AB5N3100028",
    price: 36_900,
    oldPrice: 39_500,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "18,700mi",
    mileage: 18_700,
    bodyType: "Hatchback",
    match: 84,
    labels: ["Price Drop"],
    owners: 1,
    extColorName: "Army Green",
    extColorCode: "#4B5A3D",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Gasoline",
    drivetrain: "AWD",
    transmission: "Manual",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: [...BASE_EXT, "LED Fog"],
      performance: ["AWD/4WD", "Turbo", "Sport Mode", "Adaptive Suspension"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 29,
    title: "2023 Toyota Land Cruiser",
    make: "toyota",
    model: "land-cruiser",
    variant: "first-edition",
    year: 2023,
    vin: "JTMCY7AJ5P4100029",
    price: 87_500,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "9,400mi",
    mileage: 13_500,
    bodyType: "SUV",
    match: 96,
    labels: ["Excellent Price"],
    owners: 2,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Saddle Tan",
    intColorCode: "#9C6B3D",
    fuelType: "Hybrid",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: TRD_EXT,
      performance: ["AWD/4WD", "Multi-Terrain", "Crawl Control", "Locking Diff", "Trailer Sway"],
    },
    seatingCapacity: ["Third Row", "7 Passenger", "Split Folding"],
  },
  {
    id: 30,
    title: "2024 Toyota Mirai Limited",
    make: "toyota",
    model: "mirai",
    variant: "limited",
    year: 2024,
    vin: "JTDAAAAF5R1100030",
    price: 19_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "1,200mi",
    mileage: 10_000,
    bodyType: "Sedan",
    match: 68,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
    fuelType: "Hydrogen",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: [],
    },
    seatingCapacity: [],
  },
  {
    id: 31,
    title: "2022 Toyota Camry Hybrid LE",
    make: "toyota",
    model: "camry",
    variant: "hybrid-le",
    year: 2022,
    vin: "4T1C31AK7NU100031",
    price: 25_900,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "42,100mi",
    mileage: 38_000,
    bodyType: "Sedan",
    match: 61,
    labels: ["Low Price"],
    owners: 3,
    extColorName: "Army Green",
    extColorCode: "#4B5A3D",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
    fuelType: "Hybrid",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Hybrid"],
    },
    seatingCapacity: [],
  },
  {
    id: 32,
    title: "2023 Toyota Corolla Hatchback XSE",
    make: "toyota",
    model: "corolla-hatchback",
    variant: "xse",
    year: 2023,
    vin: "JTND4MBE5P3100032",
    price: 17_500,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "16,300mi",
    mileage: 16_300,
    bodyType: "Hatchback",
    match: 77,
    labels: ["Good Price"],
    owners: 2,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Sport Mode"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 33,
    title: "2024 Toyota Venza Nightshade",
    make: "toyota",
    model: "venza",
    variant: "nightshade",
    year: 2024,
    vin: "JTEBU5JR3R5100033",
    price: 38_200,
    oldPrice: 40_900,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "7,500mi",
    mileage: 12_500,
    bodyType: "SUV",
    match: 83,
    labels: ["Price Drop"],
    owners: 1,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: [...FULL_EXT, "Folding Mirrors"],
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: [],
  },
  {
    id: 34,
    title: "2021 Toyota RAV4 Prime SE",
    make: "toyota",
    model: "rav4-prime",
    variant: "se",
    year: 2021,
    vin: "2T3A1RFV3MW100034",
    price: 37_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "29,800mi",
    mileage: 29_800,
    bodyType: "SUV",
    match: 79,
    labels: [],
    owners: 3,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
    fuelType: "Plug-in Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: [...BASE_SAFETY, "BSM", "ACC", "RCTA"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: BASE_EXT,
      performance: ["Hybrid", "PHEV", "AWD/4WD"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 35,
    title: "2023 Toyota Highlander Bronze Edition",
    make: "toyota",
    model: "highlander",
    variant: "bronze-edition",
    year: 2023,
    vin: "5TDFZRBH7PS100035",
    price: 44_200,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "13,400mi",
    mileage: 13_400,
    bodyType: "SUV",
    match: 87,
    labels: ["Excellent Price"],
    owners: 2,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: FULL_TECH,
      exterior: TRD_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: ["Third Row", "7 Passenger", "Captain's Chairs"],
  },
  {
    id: 36,
    title: "2024 Toyota Tacoma Limited — Truck",
    make: "toyota",
    model: "tacoma",
    variant: "limited",
    year: 2024,
    vin: "3TMCZ5AN7RM100036",
    price: 48_800,
    image: "/images/vehicles/truck.webp",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "5,600mi",
    mileage: 11_000,
    bodyType: "Truck",
    match: 90,
    labels: ["Truck"],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
    fuelType: "Gasoline",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: MID_TECH,
      exterior: TRUCK_EXT,
      performance: ["AWD/4WD", "Multi-Terrain", "Trailer Sway"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 37,
    title: "2022 Toyota Tundra SR5 — Truck",
    make: "toyota",
    model: "tundra",
    variant: "sr5",
    year: 2022,
    vin: "5TFDY5F18NX100037",
    price: 42_500,
    oldPrice: 45_200,
    image: "/images/vehicles/truck.webp",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "33,700mi",
    mileage: 33_700,
    bodyType: "Truck",
    match: 65,
    labels: ["Price Drop", "Low Price", "Truck"],
    owners: 2,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
    fuelType: "Gasoline",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: [...BASE_EXT, "Tow Package"],
      performance: ["AWD/4WD"],
    },
    seatingCapacity: [],
  },
  {
    id: 38,
    title: "2023 Toyota Prius XLE",
    make: "toyota",
    model: "prius",
    variant: "xle",
    year: 2023,
    vin: "JTDKN3DP3P3100038",
    price: 31_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "11,900mi",
    mileage: 11_900,
    bodyType: "Sedan",
    match: 81,
    labels: ["Good Price"],
    owners: 3,
    extColorName: "Army Green",
    extColorCode: "#4B5A3D",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
    fuelType: "Hybrid",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 39,
    title: "2024 Toyota 4Runner Limited",
    make: "toyota",
    model: "4runner",
    variant: "limited",
    year: 2024,
    vin: "JTEBU5JR5R5100039",
    price: 51_200,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "3,800mi",
    mileage: 12_000,
    bodyType: "SUV",
    match: 93,
    labels: [],
    owners: 1,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
    fuelType: "Gasoline",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: MID_TECH,
      exterior: FULL_EXT,
      performance: ["AWD/4WD", "Multi-Terrain", "Crawl Control"],
    },
    seatingCapacity: ["Third Row", "7 Passenger"],
  },
  {
    id: 40,
    title: "2021 Toyota HiAce GL Commuter",
    make: "toyota",
    model: "hiace",
    variant: "gl-commuter",
    year: 2021,
    vin: "5TDKRKEC3MS100040",
    price: 36_900,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "38,500mi",
    mileage: 38_500,
    bodyType: "Van",
    match: 59,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Graphite",
    intColorCode: "#474B50",
    fuelType: "Gasoline",
    drivetrain: "RWD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: [],
    },
    seatingCapacity: ["Third Row", "8 Passenger"],
  },
  {
    id: 41,
    title: "2023 Toyota Crown Limited",
    make: "toyota",
    model: "crown",
    variant: "limited",
    year: 2023,
    vin: "JTHDP5BC7P5100041",
    price: 47_500,
    oldPrice: 50_800,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "10,200mi",
    mileage: 10_200,
    bodyType: "Sedan",
    match: 85,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Hybrid",
    drivetrain: "AWD",
    transmission: "CVT",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["Hybrid", "AWD/4WD"],
    },
    seatingCapacity: [],
  },
  {
    id: 42,
    title: "2024 Toyota GR86 Track",
    make: "toyota",
    model: "gr86",
    variant: "track",
    year: 2024,
    vin: "JF1ZNAE14R8100042",
    price: 33_900,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "2,400mi",
    mileage: 10_500,
    bodyType: "Sedan",
    match: 88,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Gasoline",
    drivetrain: "RWD",
    transmission: "Manual",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Sport Mode", "Adaptive Suspension"],
    },
    seatingCapacity: [],
  },
  {
    id: 43,
    title: "2022 Toyota MR2 Spyder Premium",
    make: "toyota",
    model: "mr2-spyder",
    variant: "premium",
    year: 2022,
    vin: "WZ1DB0C02NW100043",
    price: 44_500,
    image: "/images/vehicles/convertible.webp",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "19,600mi",
    mileage: 19_600,
    bodyType: "Convertible",
    match: 73,
    labels: [],
    owners: 2,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
    fuelType: "Gasoline",
    drivetrain: "RWD",
    transmission: "Manual",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: ["Sport Mode", "Turbo"],
    },
    seatingCapacity: [],
  },
  {
    id: 44,
    title: "2023 Toyota bZ4X XLE",
    make: "toyota",
    model: "bz4x",
    variant: "xle",
    year: 2023,
    vin: "JTMAB3FV7P5100044",
    price: 39_800,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "8,700mi",
    mileage: 13_000,
    bodyType: "SUV",
    match: 80,
    labels: ["Good Price"],
    owners: 3,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Electric",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: [...BASE_SAFETY, "BSM", "RCTA"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: BASE_EXT,
      performance: [],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 45,
    title: "2024 Toyota Avalon Limited",
    make: "toyota",
    model: "avalon",
    variant: "limited",
    year: 2024,
    vin: "4T1FZ1FB5RU100045",
    price: 38_500,
    oldPrice: 41_200,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "4,100mi",
    mileage: 12_000,
    bodyType: "Sedan",
    match: 91,
    labels: ["Price Drop"],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Saddle Tan",
    intColorCode: "#9C6B3D",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: FULL_EXT,
      performance: ["V6"],
    },
    seatingCapacity: [],
  },
  {
    id: 46,
    title: "2021 Toyota C-HR Limited",
    make: "toyota",
    model: "c-hr",
    variant: "limited",
    year: 2021,
    vin: "NMTKHMBX5MR100046",
    price: 24_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "36,200mi",
    mileage: 36_200,
    bodyType: "SUV",
    match: 56,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Graphite",
    intColorCode: "#474B50",
    fuelType: "Gasoline",
    drivetrain: "FWD",
    transmission: "CVT",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: BASE_EXT,
      performance: [],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 47,
    title: "2023 Toyota Sequoia TRD Pro",
    make: "toyota",
    model: "sequoia",
    variant: "trd-pro",
    year: 2023,
    vin: "5TDYY5G16PS100047",
    price: 72_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "12,800mi",
    mileage: 12_800,
    bodyType: "SUV",
    match: 94,
    labels: ["Excellent Price"],
    owners: 3,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
    fuelType: "Hybrid",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: FULL_COMFORT,
      tech: FULL_TECH,
      exterior: TRD_EXT,
      performance: [
        "Hybrid",
        "AWD/4WD",
        "TRD Suspension",
        "Multi-Terrain",
        "Crawl Control",
        "Locking Diff",
      ],
    },
    seatingCapacity: ["Third Row", "8 Passenger", "Captain's Chairs"],
  },
  {
    id: 48,
    title: "2024 Toyota GR Corolla Circuit",
    make: "toyota",
    model: "gr-corolla",
    variant: "circuit",
    year: 2024,
    vin: "JTEAC3AB7R3100048",
    price: 44_900,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "1,500mi",
    mileage: 10_000,
    bodyType: "Hatchback",
    match: 97,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Gasoline",
    drivetrain: "AWD",
    transmission: "Manual",
    inspection160: false,
    features: {
      safety: BASE_SAFETY,
      comfort: BASE_COMFORT,
      tech: BASE_TECH,
      exterior: [...BASE_EXT, "LED Fog"],
      performance: ["AWD/4WD", "Turbo", "Sport Mode", "Adaptive Suspension"],
    },
    seatingCapacity: ["Split Folding"],
  },
  {
    id: 49,
    title: "2022 Toyota Land Cruiser Heritage",
    make: "toyota",
    model: "land-cruiser",
    variant: "heritage",
    year: 2022,
    vin: "JTMCY7AJ3N4100049",
    price: 79_900,
    oldPrice: 85_500,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,300mi",
    mileage: 24_300,
    bodyType: "SUV",
    match: 89,
    labels: ["Price Drop"],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
    fuelType: "Hybrid",
    drivetrain: "4WD",
    transmission: "Automatic",
    inspection160: true,
    features: {
      safety: FULL_SAFETY,
      comfort: LUXURY_COMFORT,
      tech: FULL_TECH,
      exterior: TRD_EXT,
      performance: [
        "Hybrid",
        "AWD/4WD",
        "Multi-Terrain",
        "Crawl Control",
        "Locking Diff",
        "Trailer Sway",
      ],
    },
    seatingCapacity: ["Third Row", "7 Passenger", "Split Folding"],
  },
  {
    id: 50,
    title: "2023 Toyota Mirai XLE",
    make: "toyota",
    model: "mirai",
    variant: "xle",
    year: 2023,
    vin: "JTDAAAAF7P1100050",
    price: 48_200,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "6,800mi",
    mileage: 11_500,
    bodyType: "Sedan",
    match: 70,
    labels: ["Good Price"],
    owners: 1,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
    fuelType: "Hydrogen",
    drivetrain: "FWD",
    transmission: "Automatic",
    inspection160: false,
    features: {
      safety: [...BASE_SAFETY, "BSM", "ACC"],
      comfort: MID_COMFORT,
      tech: MID_TECH,
      exterior: BASE_EXT,
      performance: [],
    },
    seatingCapacity: [],
  },
];
