export interface VehicleEstimation {
  creditScore: string;
  apr: string;
  termLength: string;
  estimatedMonthlyPayment: string;
}

export interface Vehicle {
  id: number;
  title: string;
  make: string;
  model: string;
  variant: string;
  year: number;
  vin: string;
  price: number;
  oldPrice?: number;
  image: string | string[];
  miles: string;
  odometer: string;
  match: number;
  labels: string[];
  owners: number;
  extColorName: string;
  extColorCode: string;
  intColorName: string;
  intColorCode: string;
  estimation?: VehicleEstimation;
}

/** Compute a default estimation summary from the vehicle price. */
export function getVehicleEstimation(vehicle: Vehicle): VehicleEstimation {
  if (vehicle.estimation) {
    return vehicle.estimation;
  }
  const apr = 5.49;
  const termMonths = 60;
  const downPayment = 2500;
  const principal = vehicle.price - downPayment;
  const monthlyRate = apr / 100 / 12;
  const monthly = Math.round((principal * monthlyRate) / (1 - (1 + monthlyRate) ** -termMonths));
  return {
    creditScore: "Excellent (800+) FICO® Score",
    apr: `${apr}%`,
    termLength: `$${downPayment.toLocaleString()}`,
    estimatedMonthlyPayment: `$${monthly}`,
  };
}

export const mockVehicles: Vehicle[] = [
  {
    id: 1,
    title: "2023 Toyota Corolla Cross",
    make: "toyota",
    model: "corolla-cross",
    variant: "le",
    year: 2023,
    vin: "JTDEPMAE5PJ100001",
    price: 31_250,
    image: [
      "/images/vehicles/corolla-cross.png",
      "/images/vehicles/rav4-blue.png",
      "/images/vehicles/rav4-white.png",
    ],
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "18,000mi",
    match: 39,
    labels: [],
    owners: 2,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Black SofTex",
    intColorCode: "#1B1B1B",
  },
  {
    id: 2,
    title: "2022 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-xle",
    year: 2022,
    vin: "2T3P1RFV8NW100002",
    price: 31_250,
    image: ["/images/vehicles/rav4-blue.png", "/images/vehicles/corolla-cross.png"],
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,600mi",
    match: 56,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
  },
  {
    id: 3,
    title: "2023 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-limited",
    year: 2023,
    vin: "2T3P1RFV5PW100003",
    price: 33_250,
    oldPrice: 34_995,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    match: 79,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 4,
    title: "2023 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-se",
    year: 2023,
    vin: "2T3P1RFV3PW100004",
    price: 33_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    match: 79,
    labels: [],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 5,
    title: "2024 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-xle-premium",
    year: 2024,
    vin: "2T3P1RFV0RW100005",
    price: 29_990,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,500mi",
    match: 85,
    labels: [],
    owners: 2,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
  },
  {
    id: 6,
    title: "2022 Toyota Yaris Cross Hybrid Active",
    make: "toyota",
    model: "yaris-cross",
    variant: "hybrid-active",
    year: 2022,
    vin: "JTDKN3DU5N0100006",
    price: 30_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "16,000mi",
    match: 54,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 7,
    title: "2023 Toyota Corolla Cross",
    make: "toyota",
    model: "corolla-cross",
    variant: "xle",
    year: 2023,
    vin: "JTDEPMAE7PJ100007",
    price: 31_250,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "18,000mi",
    match: 81,
    labels: [],
    owners: 3,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 8,
    title: "2024 Toyota RAV4 Hybrid",
    make: "toyota",
    model: "rav4",
    variant: "hybrid-limited",
    year: 2024,
    vin: "2T3P1RFV5RW100008",
    price: 33_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "5,000mi",
    match: 57,
    labels: [],
    owners: 2,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 9,
    title: "2020 Toyota Venza Limited Edition",
    make: "toyota",
    model: "venza",
    variant: "limited",
    year: 2020,
    vin: "JTEBU5JR5L5100009",
    price: 32_000,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "9,000mi",
    match: 74,
    labels: [],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 10,
    title: "2022 Toyota Yaris Cross Hybrid Active",
    make: "toyota",
    model: "yaris-cross",
    variant: "hybrid-active",
    year: 2022,
    vin: "JTDKN3DU3N0100010",
    price: 24_250,
    image: "/images/vehicles/yaris-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "11,050mi",
    match: 72,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 11,
    title: "2025 Toyota RAV4 Limited Edition",
    make: "toyota",
    model: "rav4",
    variant: "limited",
    year: 2025,
    vin: "2T3P1RFV7SW100011",
    price: 30_900,
    image: "/images/vehicles/rav4-white.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "15,000mi",
    match: 55,
    labels: ["Low Price"],
    owners: 1,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
  },
  {
    id: 12,
    title: "2020 Toyota Corolla Cross Limited Edition",
    make: "toyota",
    model: "corolla-cross",
    variant: "limited",
    year: 2020,
    vin: "JTDEPMAE0L0100012",
    price: 31_250,
    oldPrice: 34_568,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "17,200mi",
    match: 76,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 13,
    title: "2025 Toyota RAV4 Limited Edition",
    make: "toyota",
    model: "rav4",
    variant: "limited",
    year: 2025,
    vin: "2T3P1RFV9SW100013",
    price: 34_250,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "21,000mi",
    match: 74,
    labels: [],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 14,
    title: "2023 Toyota Camry XSE",
    make: "toyota",
    model: "camry",
    variant: "xse",
    year: 2023,
    vin: "4T1K61AK5PU100014",
    price: 28_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "12,500mi",
    match: 88,
    labels: ["Good Price"],
    owners: 1,
    extColorName: "Wind Chill Pearl",
    extColorCode: "#F6F7F2",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
  },
  {
    id: 15,
    title: "2024 Toyota Highlander Hybrid",
    make: "toyota",
    model: "highlander",
    variant: "hybrid-platinum",
    year: 2024,
    vin: "5TDFZRBH5RS100015",
    price: 45_990,
    oldPrice: 48_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "8,200mi",
    match: 91,
    labels: ["Price Drop"],
    owners: 2,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 16,
    title: "2022 Toyota Tacoma TRD Pro",
    make: "toyota",
    model: "tacoma",
    variant: "trd-pro",
    year: 2022,
    vin: "3TMCZ5AN5NM100016",
    price: 42_750,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "28,400mi",
    match: 67,
    labels: [],
    owners: 3,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
  },
  {
    id: 17,
    title: "2023 Toyota Tundra CrewMax",
    make: "toyota",
    model: "tundra",
    variant: "crewmax-sr5",
    year: 2023,
    vin: "5TFDY5F16PX100017",
    price: 52_900,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "15,800mi",
    match: 72,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 18,
    title: "2024 Toyota Prius Prime",
    make: "toyota",
    model: "prius",
    variant: "prime-xle",
    year: 2024,
    vin: "JTDKN3DP5R3100018",
    price: 34_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "3,200mi",
    match: 94,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 19,
    title: "2021 Toyota 4Runner TRD Off-Road",
    make: "toyota",
    model: "4runner",
    variant: "trd-off-road",
    year: 2021,
    vin: "JTEBU5JR3M5100019",
    price: 39_900,
    oldPrice: 42_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "35,600mi",
    match: 63,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
  },
  {
    id: 20,
    title: "2023 Toyota Sienna Platinum",
    make: "toyota",
    model: "sienna",
    variant: "platinum",
    year: 2023,
    vin: "5TDKRKEC5PS100020",
    price: 48_750,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "19,200mi",
    match: 78,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 21,
    title: "2024 Toyota Crown Platinum",
    make: "toyota",
    model: "crown",
    variant: "platinum",
    year: 2024,
    vin: "JTHDP5BC5R5100021",
    price: 51_200,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "6,100mi",
    match: 86,
    labels: ["Good Price"],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 22,
    title: "2022 Toyota GR86 Premium",
    make: "toyota",
    model: "gr86",
    variant: "premium",
    year: 2022,
    vin: "JF1ZNAE12N8100022",
    price: 29_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "22,300mi",
    match: 71,
    labels: [],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 23,
    title: "2023 Toyota Supra 3.0",
    make: "toyota",
    model: "supra",
    variant: "3-0-premium",
    year: 2023,
    vin: "WZ1DB0C08PW100023",
    price: 54_900,
    oldPrice: 58_200,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "11,500mi",
    match: 82,
    labels: ["Price Drop", "Excellent Price"],
    owners: 3,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Light Gray",
    intColorCode: "#D7D8DA",
  },
  {
    id: 24,
    title: "2024 Toyota bZ4X Limited",
    make: "toyota",
    model: "bz4x",
    variant: "limited",
    year: 2024,
    vin: "JTMAB3FV5R5100024",
    price: 43_500,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "4,800mi",
    match: 89,
    labels: [],
    owners: 2,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 25,
    title: "2021 Toyota Avalon TRD",
    make: "toyota",
    model: "avalon",
    variant: "trd",
    year: 2021,
    vin: "4T1FZ1FB3MU100025",
    price: 32_400,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "31,200mi",
    match: 58,
    labels: ["Low Price"],
    owners: 1,
    extColorName: "Midnight Black Metallic",
    extColorCode: "#0F1115",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 26,
    title: "2023 Toyota C-HR Nightshade",
    make: "toyota",
    model: "c-hr",
    variant: "nightshade",
    year: 2023,
    vin: "NMTKHMBX0PR100026",
    price: 27_900,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "14,600mi",
    match: 75,
    labels: ["Good Price"],
    owners: 2,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
  },
  {
    id: 27,
    title: "2024 Toyota Sequoia Capstone",
    make: "toyota",
    model: "sequoia",
    variant: "capstone",
    year: 2024,
    vin: "5TDYY5G14RS100027",
    price: 78_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "2,100mi",
    match: 92,
    labels: [],
    owners: 3,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 28,
    title: "2022 Toyota GR Corolla Core",
    make: "toyota",
    model: "gr-corolla",
    variant: "core",
    year: 2022,
    vin: "JTEAC3AB5N3100028",
    price: 36_900,
    oldPrice: 39_500,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "18,700mi",
    match: 84,
    labels: ["Price Drop"],
    owners: 1,
    extColorName: "Army Green",
    extColorCode: "#4B5A3D",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 29,
    title: "2023 Toyota Land Cruiser",
    make: "toyota",
    model: "land-cruiser",
    variant: "first-edition",
    year: 2023,
    vin: "JTMCY7AJ5P4100029",
    price: 87_500,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "9,400mi",
    match: 96,
    labels: ["Excellent Price"],
    owners: 2,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Saddle Tan",
    intColorCode: "#9C6B3D",
  },
  {
    id: 30,
    title: "2024 Toyota Mirai Limited",
    make: "toyota",
    model: "mirai",
    variant: "limited",
    year: 2024,
    vin: "JTDAAAAF5R1100030",
    price: 52_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "1,200mi",
    match: 68,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
  },
  {
    id: 31,
    title: "2022 Toyota Camry Hybrid LE",
    make: "toyota",
    model: "camry",
    variant: "hybrid-le",
    year: 2022,
    vin: "4T1C31AK7NU100031",
    price: 25_900,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "42,100mi",
    match: 61,
    labels: ["Low Price"],
    owners: 3,
    extColorName: "Army Green",
    extColorCode: "#4B5A3D",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
  },
  {
    id: 32,
    title: "2023 Toyota Corolla Hatchback XSE",
    make: "toyota",
    model: "corolla-hatchback",
    variant: "xse",
    year: 2023,
    vin: "JTND4MBE5P3100032",
    price: 26_500,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "16,300mi",
    match: 77,
    labels: ["Good Price"],
    owners: 2,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 33,
    title: "2024 Toyota Venza Nightshade",
    make: "toyota",
    model: "venza",
    variant: "nightshade",
    year: 2024,
    vin: "JTEBU5JR3R5100033",
    price: 38_200,
    oldPrice: 40_900,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "7,500mi",
    match: 83,
    labels: ["Price Drop"],
    owners: 1,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Ash Fabric",
    intColorCode: "#CFCBC2",
  },
  {
    id: 34,
    title: "2021 Toyota RAV4 Prime SE",
    make: "toyota",
    model: "rav4-prime",
    variant: "se",
    year: 2021,
    vin: "2T3A1RFV3MW100034",
    price: 37_500,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "29,800mi",
    match: 79,
    labels: [],
    owners: 3,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Cockpit Red",
    intColorCode: "#7E1F29",
  },
  {
    id: 35,
    title: "2023 Toyota Highlander Bronze Edition",
    make: "toyota",
    model: "highlander",
    variant: "bronze-edition",
    year: 2023,
    vin: "5TDFZRBH7PS100035",
    price: 44_200,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "13,400mi",
    match: 87,
    labels: ["Excellent Price"],
    owners: 2,
    extColorName: "Celestial Silver",
    extColorCode: "#B8BEC4",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 36,
    title: "2024 Toyota Tacoma Limited",
    make: "toyota",
    model: "tacoma",
    variant: "limited",
    year: 2024,
    vin: "3TMCZ5AN7RM100036",
    price: 47_800,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "5,600mi",
    match: 90,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 37,
    title: "2022 Toyota Tundra SR5",
    make: "toyota",
    model: "tundra",
    variant: "sr5",
    year: 2022,
    vin: "5TFDY5F18NX100037",
    price: 41_500,
    oldPrice: 44_200,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "33,700mi",
    match: 65,
    labels: ["Price Drop", "Low Price"],
    owners: 2,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 38,
    title: "2023 Toyota Prius XLE",
    make: "toyota",
    model: "prius",
    variant: "xle",
    year: 2023,
    vin: "JTDKN3DP3P3100038",
    price: 31_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "11,900mi",
    match: 81,
    labels: ["Good Price"],
    owners: 3,
    extColorName: "Army Green",
    extColorCode: "#4B5A3D",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 39,
    title: "2024 Toyota 4Runner Limited",
    make: "toyota",
    model: "4runner",
    variant: "limited",
    year: 2024,
    vin: "JTEBU5JR5R5100039",
    price: 51_200,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "3,800mi",
    match: 93,
    labels: [],
    owners: 1,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 40,
    title: "2021 Toyota Sienna XLE",
    make: "toyota",
    model: "sienna",
    variant: "xle",
    year: 2021,
    vin: "5TDKRKEC3MS100040",
    price: 36_900,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "38,500mi",
    match: 59,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Graphite",
    intColorCode: "#474B50",
  },
  {
    id: 41,
    title: "2023 Toyota Crown Limited",
    make: "toyota",
    model: "crown",
    variant: "limited",
    year: 2023,
    vin: "JTHDP5BC7P5100041",
    price: 47_500,
    oldPrice: 50_800,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "10,200mi",
    match: 85,
    labels: ["Price Drop"],
    owners: 3,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 42,
    title: "2024 Toyota GR86 Track",
    make: "toyota",
    model: "gr86",
    variant: "track",
    year: 2024,
    vin: "JF1ZNAE14R8100042",
    price: 33_900,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "2,400mi",
    match: 88,
    labels: ["Excellent Price"],
    owners: 1,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 43,
    title: "2022 Toyota Supra 2.0",
    make: "toyota",
    model: "supra",
    variant: "2-0",
    year: 2022,
    vin: "WZ1DB0C02NW100043",
    price: 44_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "19,600mi",
    match: 73,
    labels: [],
    owners: 2,
    extColorName: "Ice Cap",
    extColorCode: "#F7F7F5",
    intColorName: "Boulder",
    intColorCode: "#6A6A64",
  },
  {
    id: 44,
    title: "2023 Toyota bZ4X XLE",
    make: "toyota",
    model: "bz4x",
    variant: "xle",
    year: 2023,
    vin: "JTMAB3FV7P5100044",
    price: 39_800,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "8,700mi",
    match: 80,
    labels: ["Good Price"],
    owners: 3,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 45,
    title: "2024 Toyota Avalon Limited",
    make: "toyota",
    model: "avalon",
    variant: "limited",
    year: 2024,
    vin: "4T1FZ1FB5RU100045",
    price: 38_500,
    oldPrice: 41_200,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "4,100mi",
    match: 91,
    labels: ["Price Drop"],
    owners: 1,
    extColorName: "Ruby Flare Pearl",
    extColorCode: "#8B1A24",
    intColorName: "Saddle Tan",
    intColorCode: "#9C6B3D",
  },
  {
    id: 46,
    title: "2021 Toyota C-HR Limited",
    make: "toyota",
    model: "c-hr",
    variant: "limited",
    year: 2021,
    vin: "NMTKHMBX5MR100046",
    price: 24_800,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "36,200mi",
    match: 56,
    labels: ["Low Price"],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Graphite",
    intColorCode: "#474B50",
  },
  {
    id: 47,
    title: "2023 Toyota Sequoia TRD Pro",
    make: "toyota",
    model: "sequoia",
    variant: "trd-pro",
    year: 2023,
    vin: "5TDYY5G16PS100047",
    price: 72_500,
    image: "/images/vehicles/rav4-white.png",
    miles: "Park Place Toyota - 8.5mi",
    odometer: "12,800mi",
    match: 94,
    labels: ["Excellent Price"],
    owners: 3,
    extColorName: "Blueprint",
    extColorCode: "#1D3F73",
    intColorName: "Moonstone",
    intColorCode: "#9EA6AD",
  },
  {
    id: 48,
    title: "2024 Toyota GR Corolla Circuit",
    make: "toyota",
    model: "gr-corolla",
    variant: "circuit",
    year: 2024,
    vin: "JTEAC3AB7R3100048",
    price: 44_900,
    image: "/images/vehicles/corolla-cross.png",
    miles: "Toyota of Irving - 5.7mi",
    odometer: "1,500mi",
    match: 97,
    labels: [],
    owners: 1,
    extColorName: "Magnetic Gray Metallic",
    extColorCode: "#646A70",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
  {
    id: 49,
    title: "2022 Toyota Land Cruiser Heritage",
    make: "toyota",
    model: "land-cruiser",
    variant: "heritage",
    year: 2022,
    vin: "JTMCY7AJ3N4100049",
    price: 79_900,
    oldPrice: 85_500,
    image: "/images/vehicles/rav4-blue.png",
    miles: "Toyota of Fort Worth - 6.1mi",
    odometer: "24,300mi",
    match: 89,
    labels: ["Price Drop"],
    owners: 2,
    extColorName: "Supersonic Red",
    extColorCode: "#C90F2B",
    intColorName: "Harvest Beige",
    intColorCode: "#D5C1A1",
  },
  {
    id: 50,
    title: "2023 Toyota Mirai XLE",
    make: "toyota",
    model: "mirai",
    variant: "xle",
    year: 2023,
    vin: "JTDAAAAF7P1100050",
    price: 48_200,
    image: "/images/vehicles/yaris-cross.png",
    miles: "AutoNation Toyota - 3.2mi",
    odometer: "6,800mi",
    match: 70,
    labels: ["Good Price"],
    owners: 1,
    extColorName: "Cavalry Blue",
    extColorCode: "#4E6E8C",
    intColorName: "Macadamia",
    intColorCode: "#9A8064",
  },
];
